#!/usr/bin/env fish

# Read argv
getopts $argv | while read -l key value
        if test "$key" = "_"
                set edit_fname $value
        else
                set new_argv "$key $value" $new_argv
        end
end


# Create a temp file, copy the file we want to edit
# to the temp file, edit the temp file
set -l temp_name (mktemp editing.XXXX)
doas cat $edit_fname > $temp_name
set -l argv $temp_name
eval "$EDITOR $temp_name"

# Make sure nothing went wrong with the editing
# and then check if the file was actually edited
if test "$status" -eq 0
        diff $temp_name $edit_fname > /dev/null
        if test "$status" -eq 0
                echo "File was not changed!" >&2
        else
                doas cp $temp_name $edit_fname
        end
end
