#!/usr/bin/env fish

## Spawn a dialog box and ask the user
## whether they really want to suspend or not

set date_str (printf "[%s]" (date -u) )
Xdialog --center --wmclass 'Xdialog' --yesno "Are you sure you want to suspend?" 0 0

if test "$status" = "0"
        echo $date_str "Suspending!" 1>&2
        doas acpiconf -s 3
else
        echo $date_str "Did not suspend" 1>&2
end
